apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"monitoring-influxdb","namespace":"kube-system","selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-influxdb","uid":"c6bcd76b-9108-11e7-83cd-000c29db7697","resourceVersion":"13733926","generation":1,"creationTimestamp":"2017-09-04T00:34:13Z","labels":{"k8s-app":"influxdb","task":"monitoring"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"influxdb","task":"monitoring"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"influxdb","task":"monitoring"}},"spec":{"volumes":[{"name":"influxdb-storage","emptyDir":{}}],"containers":[{"name":"influxdb","image":"docker.io/influxdb","resources":{},"volumeMounts":[{"name":"influxdb-storage","mountPath":"/data"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":1,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-09-04T00:34:13Z","lastTransitionTime":"2017-09-04T00:34:13Z","reason":"MinimumReplicasAvailable","message":"Deployment
      has minimum availability."}]}}'
  creationTimestamp: 2017-09-04T23:13:15Z
  generation: 1
  labels:
    k8s-app: influxdb
    task: monitoring
  name: monitoring-influxdb
  namespace: kube-system
  resourceVersion: "13821224"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-influxdb
  uid: a1741634-91c6-11e7-83cd-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: influxdb
        task: monitoring
    spec:
      containers:
      - image: docker.io/influxdb
        imagePullPolicy: Always
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: influxdb-storage
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-09-04T23:13:15Z
    lastUpdateTime: 2017-09-04T23:13:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
