apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"heapster","namespace":"kube-system","selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/deployments/heapster","uid":"17c9ab88-9100-11e7-83cd-000c29db7697","resourceVersion":"13733931","generation":1,"creationTimestamp":"2017-09-03T23:32:04Z","labels":{"k8s-app":"heapster","task":"monitoring"},"annotations":{"deployment.kubernetes.io/revision":"1"}},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"heapster","task":"monitoring"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"heapster","task":"monitoring"}},"spec":{"containers":[{"name":"heapster","image":"gcr.io/google_containers/heapster-amd64:v1.4.0","command":["/heapster","--source=kubernetes:https://kubernetes.default","--sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086"],"resources":{},"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"heapster","serviceAccount":"heapster","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":1,"replicas":1,"updatedReplicas":1,"availableReplicas":1,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-09-03T23:32:04Z","lastTransitionTime":"2017-09-03T23:32:04Z","reason":"MinimumReplicasAvailable","message":"Deployment
      has minimum availability."}]}}'
  creationTimestamp: 2017-09-04T23:13:15Z
  generation: 1
  labels:
    k8s-app: heapster
    task: monitoring
  name: heapster
  namespace: kube-system
  resourceVersion: "13821215"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/heapster
  uid: a150d042-91c6-11e7-83cd-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: heapster
        task: monitoring
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
        image: gcr.io/google_containers/heapster-amd64:v1.4.0
        imagePullPolicy: IfNotPresent
        name: heapster
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: heapster
      serviceAccountName: heapster
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-09-04T23:13:15Z
    lastUpdateTime: 2017-09-04T23:13:15Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
