apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"monitoring-grafana","namespace":"kube-system","creationTimestamp":null,"labels":{"k8s-app":"grafana","task":"monitoring"}},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"grafana","task":"monitoring"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"grafana","task":"monitoring"}},"spec":{"volumes":[{"name":"ca-certificates","hostPath":{"path":"/etc/ssl/certs"}},{"name":"grafana-storage","hostPath":{"path":"/data/registry_tikejhya/vol/grafana"}},{"name":"grafana-config","hostPath":{"path":"/data/registry_tikejhya/vol/grafana_config"}}],"containers":[{"name":"grafana","image":"gcr.io/google_containers/heapster-grafana-amd64:v4.4.1","ports":[{"containerPort":3000,"protocol":"TCP"}],"env":[{"name":"INFLUXDB_HOST","value":"monitoring-influxdb"},{"name":"GF_ALLOW_SIGN_UP","value":"false"},{"name":"GF_SERVER_HTTP_PORT","value":"3000"},{"name":"GF_AUTH_BASIC_ENABLED","value":"true"},{"name":"GF_AUTH_ANONYMOUS_ENABLED","value":"true"},{"name":"GF_AUTH_ANONYMOUS_ORG_ROLE","value":"viewer"},{"name":"GF_SERVER_ROOT_URL","value":"/"}],"resources":{},"volumeMounts":[{"name":"grafana-config","mountPath":"/etc/grafana"},{"name":"ca-certificates","readOnly":true,"mountPath":"/etc/ssl/certs"},{"name":"grafana-storage","mountPath":"/var"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{}}'
  creationTimestamp: 2017-09-05T00:23:47Z
  generation: 1
  labels:
    k8s-app: grafana
    task: monitoring
  name: monitoring-grafana
  namespace: kube-system
  resourceVersion: "13826482"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-grafana
  uid: 7bacc39b-91d0-11e7-83cd-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana
        task: monitoring
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: viewer
        - name: GF_SERVER_ROOT_URL
          value: /
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.4.1
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/grafana
          name: grafana-config
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
        - mountPath: /var
          name: grafana-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certificates
      - hostPath:
          path: /data/registry_tikejhya/vol/grafana
        name: grafana-storage
      - hostPath:
          path: /data/registry_tikejhya/vol/grafana_config
        name: grafana-config
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-09-05T00:23:47Z
    lastUpdateTime: 2017-09-05T00:23:47Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
