apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-04-30T15:33:03Z
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "606418"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: 4cd96291-2dba-11e7-8cec-000c29db7697
spec:
  clusterIP: 10.254.3.100
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
