apiVersion: v1
kind: Service
metadata:
  labels:
    app: meotic-nginx
    env: prod
    proj: anepal
  name: meotic-nginx
spec:
  ports:
  - nodePort: 32524
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: meotic-nginx
    env: prod
    proj: anepal
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
