apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: grafana
    task: monitoring
  name: monitoring-grafana
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: grafana
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana
        task: monitoring
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: viewer
        - name: GF_SERVER_ROOT_URL
          value: /
        image: gcr.io/google_containers/heapster-grafana-amd64:v4.4.1
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/grafana
          name: grafana-config
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
        - mountPath: /var
          name: grafana-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certificates
      - hostPath:
          path: /data/registry_tikejhya/vol/grafana
      #- emptyDir: {}
        name: grafana-storage
      - hostPath:
          path: /data/registry_tikejhya/vol/grafana_config
        name: grafana-config
