apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"heapster","namespace":"kube-system","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true","kubernetes.io/name":"Heapster","task":"monitoring"}},"spec":{"ports":[{"port":80,"targetPort":8082}],"selector":{"k8s-app":"heapster"}},"status":{"loadBalancer":{}}}'
  creationTimestamp: 2017-09-03T23:32:04Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: Heapster
    task: monitoring
  name: heapster
  namespace: kube-system
  resourceVersion: "13725311"
  selfLink: /api/v1/namespaces/kube-system/services/heapster
  uid: 17ef31b2-9100-11e7-83cd-000c29db7697
spec:
  clusterIP: 10.254.182.229
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    k8s-app: heapster
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
