apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"monitoring-grafana","namespace":"kube-system","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true","kubernetes.io/name":"monitoring-grafana"}},"spec":{"ports":[{"protocol":"TCP","port":80,"targetPort":3000,"nodePort":32599}],"selector":{"k8s-app":"grafana"},"clusterIP":"10.254.102.74","type":"NodePort","sessionAffinity":"None"},"status":{"loadBalancer":{}}}'
  creationTimestamp: 2017-09-03T23:32:04Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
  resourceVersion: "13734488"
  selfLink: /api/v1/namespaces/kube-system/services/monitoring-grafana
  uid: 17a10425-9100-11e7-83cd-000c29db7697
spec:
  clusterIP: 10.254.102.74
  ports:
  - nodePort: 32599
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
