apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Service","apiVersion":"v1","metadata":{"name":"monitoring-influxdb","namespace":"kube-system","creationTimestamp":null,"labels":{"kubernetes.io/cluster-service":"true","kubernetes.io/name":"monitoring-influxdb","task":"monitoring"}},"spec":{"ports":[{"port":8086,"targetPort":8086}],"selector":{"k8s-app":"influxdb"}},"status":{"loadBalancer":{}}}'
  creationTimestamp: 2017-09-04T00:34:14Z
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: monitoring-influxdb
    task: monitoring
  name: monitoring-influxdb
  namespace: kube-system
  resourceVersion: "13730265"
  selfLink: /api/v1/namespaces/kube-system/services/monitoring-influxdb
  uid: c6e95f3c-9108-11e7-83cd-000c29db7697
spec:
  clusterIP: 10.254.7.227
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    k8s-app: influxdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
