apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"my-nginx","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/my-nginx","uid":"eb34840a-846e-11e7-ac1a-000c29db7697","resourceVersion":"12276632","generation":8,"creationTimestamp":"2017-08-18T23:42:38Z","labels":{"app":"my-nginx","env":"prod","proj":"anepal"},"annotations":{"deployment.kubernetes.io/revision":"8"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"my-nginx","env":"prod","proj":"anepal"}},"template":{"metadata":{"name":"my-nginx","creationTimestamp":null,"labels":{"app":"my-nginx","env":"prod","proj":"anepal"}},"spec":{"volumes":[{"name":"nginx-www-dir","hostPath":{"path":"/data/registry_tikejhya/vol/www.tikejhya.com/www"}},{"name":"nginx-log","hostPath":{"path":"/data/registry_tikejhya/vol/www.tikejhya.com/logs/nginx_log/"}},{"name":"nginx-config-tikejhya","hostPath":{"path":"/data/registry_tikejhya/brand_nginx"}}],"containers":[{"name":"my-nginx","image":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"nginx-www-dir","mountPath":"/data/www.tikejhya.com/www/"},{"name":"nginx-log","mountPath":"/data/logs/www.tikejhya.com/nginx_log/"},{"name":"nginx-config-tikejhya","mountPath":"/etc/nginx"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":8,"replicas":2,"updatedReplicas":2,"availableReplicas":2,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-08-19T00:31:03Z","lastTransitionTime":"2017-08-19T00:31:03Z","reason":"MinimumReplicasAvailable","message":"Deployment
      has minimum availability."}]}}'
  creationTimestamp: 2017-08-18T23:42:38Z
  generation: 9
  labels:
    app: my-nginx
    env: prod
    proj: anepal
  name: my-nginx
  namespace: default
  resourceVersion: "12302945"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/my-nginx
  uid: eb34840a-846e-11e7-ac1a-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
      env: prod
      proj: anepal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        env: prod
        proj: anepal
      name: my-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data/www.tikejhya.com/www/
          name: nginx-www-dir
        - mountPath: /data/logs/www.tikejhya.com/nginx_log/
          name: nginx-log
        - mountPath: /etc/nginx
          name: nginx-config-tikejhya
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/registry_tikejhya/vol/www.tikejhya.com/www
        name: nginx-www-dir
      - hostPath:
          path: /data/registry_tikejhya/vol/www.tikejhya.com/logs/nginx_log/
        name: nginx-log
      - hostPath:
          path: /data/registry_tikejhya/brand_nginx
        name: nginx-config-tikejhya
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-19T00:31:03Z
    lastUpdateTime: 2017-08-19T00:31:03Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  replicas: 1
  updatedReplicas: 1
