apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tikejhya-nginx
    env: prod
    proj: tikejhya
  name: tikejhya-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tikejhya-nginx
      env: prod
      proj: tikejhya
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tikejhya-nginx
        env: prod
        proj: tikejhya
      name: tikejhya-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: tikejhya-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data/www.tikejhya.com/www/
          name: nginx-www-dir
        - mountPath: /data/logs/www.tikejhya.com/nginx_log/
          name: nginx-log
        - mountPath: /etc/nginx
          name: nginx-config-tikejhya
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/registry_tikejhya/vol/www.tikejhya.com/www
        name: nginx-www-dir
      - hostPath:
          path: /data/registry_tikejhya/vol/www.tikejhya.com/logs/nginx_log/
        name: nginx-log
      - hostPath:
          path: /data/registry_tikejhya/brand_nginx
        name: nginx-config-tikejhya
