apiVersion: v1
kind: Service
metadata:
  labels:
    app: tikejhya-nginx
    env: prod
    proj: tikejhya
  name: tikejhya-nginx
  namespace: default
spec:
  ports:
  - nodePort: 32528
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tikejhya-nginx
    env: prod
    proj: tikejhya
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
