apiVersion: v1
kind: Service
metadata:
  labels:
    app: anepal-fpm
  name: anepal-fpm
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: anepal-fpm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
