apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2017-05-07T12:15:10Z
  generation: 3
  labels:
    app: fpm
  name: fpm
  namespace: default
  resourceVersion: "12302177"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/fpm
  uid: d0b1f7b7-331e-11e7-9512-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fpm
    spec:
      containers:
      - image: kube-master01.tikejhya.com:5000/php-fpm7-mysqli:v1
        imagePullPolicy: IfNotPresent
        name: fpm
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data/www.ashishnepal.com/www/
          name: nginx-www-dir
        - mountPath: /usr/local/etc
          name: phpfpm-config
        - mountPath: /data/logs
          name: phpfpm-logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/registry_tikejhya/php-fpm
        name: phpfpm-config
      - hostPath:
          path: /data/registry_tikejhya/vol/www.ashishnepal.com/www
        name: nginx-www-dir
      - hostPath:
          path: /data/registry_tikejhya/vol/www.ashishnepal.com/logs/fpm_log
        name: phpfpm-logs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-16T21:49:06Z
    lastUpdateTime: 2017-08-16T21:49:06Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
