apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Deployment","apiVersion":"extensions/v1beta1","metadata":{"name":"nginx","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/nginx","uid":"b5fe5261-331e-11e7-9512-000c29db7697","resourceVersion":"12280336","generation":4,"creationTimestamp":"2017-05-07T12:14:25Z","labels":{"app":"nginx","env":"prod","proj":"anepal"},"annotations":{"deployment.kubernetes.io/revision":"2"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx","env":"prod","proj":"anepal"}},"template":{"metadata":{"name":"nginx","creationTimestamp":null,"labels":{"app":"nginx","env":"prod","proj":"anepal"}},"spec":{"volumes":[{"name":"nginx-www-dir","hostPath":{"path":"/data/registry_tikejhya/vol/www.ashishnepal.com/www"}},{"name":"nginx-config","hostPath":{"path":"/data/registry_tikejhya/nginx"}},{"name":"nginx-log","hostPath":{"path":"/data/registry_tikejhya/vol/www.ashishnepal.com/logs/nginx_log/"}}],"containers":[{"name":"nginx","image":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"nginx-www-dir","mountPath":"/data/www.ashishnepal.com/www/"},{"name":"nginx-config","mountPath":"/etc/nginx"},{"name":"nginx-log","mountPath":"/data/logs/www.ashishnepal.com/nginx_log/"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{}}},"strategy":{"type":"RollingUpdate","rollingUpdate":{"maxUnavailable":1,"maxSurge":1}}},"status":{"observedGeneration":4,"replicas":2,"updatedReplicas":2,"availableReplicas":2,"conditions":[{"type":"Available","status":"True","lastUpdateTime":"2017-08-16T21:49:27Z","lastTransitionTime":"2017-08-16T21:49:27Z","reason":"MinimumReplicasAvailable","message":"Deployment
      has minimum availability."}]}}'
  creationTimestamp: 2017-05-07T12:14:25Z
  generation: 5
  labels:
    app: nginx
    env: prod
    proj: anepal
  name: nginx
  namespace: default
  resourceVersion: "12301323"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx
  uid: b5fe5261-331e-11e7-9512-000c29db7697
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: prod
      proj: anepal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        env: prod
        proj: anepal
      name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data/www.ashishnepal.com/www/
          name: nginx-www-dir
        - mountPath: /etc/nginx
          name: nginx-config
        - mountPath: /data/logs/www.ashishnepal.com/nginx_log/
          name: nginx-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/registry_tikejhya/vol/www.ashishnepal.com/www
        name: nginx-www-dir
      - hostPath:
          path: /data/registry_tikejhya/nginx
        name: nginx-config
      - hostPath:
          path: /data/registry_tikejhya/vol/www.ashishnepal.com/logs/nginx_log/
        name: nginx-log
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-08-16T21:49:27Z
    lastUpdateTime: 2017-08-16T21:49:27Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
